### PR TITLE
fix: failed when set load to be true

### PR DESCRIPTION
**Pull request by LinuxSuRen**
See https://github.com/docker/buildx/issues/59#issuecomment-616050491

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
Please hold this PR until I make sure it works well.

**Comment by LinuxSuRen** [comment]
It should be ok now. See also https://github.com/LinuxSuRen/halo/pull/1

**Review by JohnNiang — APPROVED** [review]
/approve

The [check](https://github.com/LinuxSuRen/halo/actions/runs/6964657722/job/18952265754?pr=1) looks good to me.

Thank you for your contribution!

**Pull request merged**
